### PR TITLE
Exception handling

### LINKED ISSUE #382: warp: no exception upon an empty request
I registered an exception handler through `setOnException.`

When I send some junk instead of a request, I see an exception, as expected:

```
Warp: Invalid first line of request: "asdf"
```

However, if I send a single newline, the client gets back `500 Something went wrong`, but no exception is printed.

I think the property that any 500 error is logged on the server side is a very desirable one.

This is warp-3.0.2.3; apologies if this has been fixed in a later version.

### PR DESCRIPTION
**Pull request by kazu-yamamoto**
Trying to fix #382.

- EOF is now `ConnectionClosedByPeer` instead of `NotEnoughLines []`
- `onE` does not ignore `NotEnoughLines []`
- `defaultOnException` and `defaultOnExceptionResponse` are exported
- `defaultOnException and defaultOnExceptionResponse` sends 400 or 500
- Documentation is updated

Behavior:

- A single line:

> Incomplete request headers, received: []

and 400 response

- Junk:

> Warp: Invalid first line of request: "junk"

and 400 response

- EOF:

> Warp: Client closed connection prematurely

and no response

### CODE REVIEW

File: warp/Network/Wai/Handler/Warp/Run.hs [hunk 1]
```diff
@@ -179,9 +179,7 @@ runSettingsConnectionMakerSecure set getConnMaker app = do
                    f
 
 onE :: Settings -> Maybe Request -> SomeException -> IO ()
-onE set mreq e = case fromException e of
-    Just (NotEnoughLines []) -> return ()
-    _                        -> settingsOnException set mreq e
+onE set mreq e = settingsOnException set mreq e
```
Comment (snoyberg) [inline warp/Network/Wai/Handler/Warp/Run.hs]: Maybe just replace usage of `onE` with `settingsOnException`?

Comment (kazu-yamamoto) [inline warp/Network/Wai/Handler/Warp/Run.hs]: Thanks. It's done on master.
